### ISSUE TITLE
Error en lectura de metadata cuando es ~~

### ISSUE THREAD

**Issue by junmin** [nodecfdi/sat-ws-descarga-masiva#23]
Hola, hay un error en lectura de metadata cuando en una linea (cfdi) no viene toda la informacion, es decir, puede venir ~~  asi seguidos para algunos campos vacios, creo que es porque en versiones anteriores de cfdi no necesita razon social para timbrar o por otras razones.

como ejemplo:
```

MUY-LARGO-UUID~A SA DE CV~XXX000000ABC~~PAC000000ABC~2022-05-06 18:20:45~2022-05-06 18:20:47~7362~I~1~

Error: Cfdi validation failed: Monto: Cast to Number failed for value "I" (type string) at path "Monto", Estatus: Path `Estatus` is required.

```

**Comment by celli33** [comment]
ok, ya ando checando cuál es el problema. Espero tener un fix a más tardar el fin de semana. Muchas gracais por el reporte

**Comment by JhonE17** [comment]
Sigo presentando el mismo problema en la lectura de la metadata

**Comment by celli33** [comment]
me podrías facilitar el archivo txt que te genera(al menos los headers), si quieres por privado o con datos editados igual puedes comunicarte conmigo vía discord https://discord.com/invite/aFGYXvX para poder checarlo más a profundidad.

**Comment by junmin** [comment]
> me podrías facilitar el archivo txt que te genera(al menos los headers), si quieres por privado o con datos editados igual puedes comunicarte conmigo vía discord https://discord.com/invite/aFGYXvX para poder checarlo más a profundidad.

solo tomas cualquier registro/archivo, y borras LOS VALOARES de razon social que hayan (sin borrar ~), es que en versiones anteriore de CFDI, permimita timbrar sin razon social.

**Comment by celli33** [comment]
ya lo pude replicar y ya tengo un fix. Espero publicarlo esta semana.

**Comment by celli33** [comment]
@JhonE17 se ha liberado la versión [1.0.0](https://github.com/nodecfdi/sat-ws-descarga-masiva/releases/tag/v1.0.0) puedes validar que el issue ya no se encuentre presente con esta versión.
