### ISSUE TITLE
Incompatibilidad entre sat-ws-descarga-masiva y @nodecfdi/cfdiutils-common

### ISSUE THREAD

**Issue by xarkamx** [nodecfdi/sat-ws-descarga-masiva#29]
Encontre un aparente error entre la versión actual de sat-ws-descarga-masiva y la versión actual de @nodecfdi/cfdiutils-common. Esta incompatibilidad se manifiesta cuando se intenta ejecutar el script de ejemplo utilizando la versión más reciente de cfdiutils-common, ya que el DOM parser no se puede obtener correctamente.

Pasos para reproducir el problema:

Instalar la última versión de sat-ws-descarga-masiva.
Instalar la última versión de @nodecfdi/cfdiutils-common.
Ejecutar el script de ejemplo.
Resultado esperado:
El script de ejemplo se ejecuta correctamente y se obtiene el DOM parser sin problemas.

Resultado actual:
El script de ejemplo falla al intentar obtener el DOM parser debido a la incompatibilidad entre las versiones de sat-ws-descarga-masiva y @nodecfdi/cfdiutils-common.

**Comment by luffynando** [comment]
Si fue debido a una actualización major sobre `@nodecfdi/cfdiutils-common`, temporalmente en lo que se actualiza `@nodecfdi/sat-ws-descarga-masiva`, utiliza la version [1.2.6](https://github.com/nodecfdi/cfdiutils-common/releases/tag/v1.2.6).

**Comment by celli33** [comment]
se ha liberado la versión [1.0.0](https://github.com/nodecfdi/sat-ws-descarga-masiva/releases/tag/v1.0.0) en donde se pasa de depender de @nodecfdi/cfdiutils-common a @nodecfdi/cfdi-core
