### ISSUE TITLE
Error 500 al intentar obtener certificados de retención

### ISSUE THREAD

**Issue by rafaelcor** [nodecfdi/sat-ws-descarga-masiva#33]
### Package version

1.0.1

### Describe el bug

Al intentar usar el servicio para obtener certificados de retención me retorna error 500

El servicio lo creo de la siguiente manera:
const service = new Service(requestBuilder, webClient, undefined, ServiceEndpoints.retenciones());

**Comment by celli33** [comment]
Hola el servicio de retenciones no funciona por parte del SAT desde hace unos 2 o 3 años.
